### ISSUE TITLE
Use ai on / off for Harm defence

### ISSUE THREAD

**Issue by walder** [walder/Skynet-IADS#76]
Described by Flogas on discord:

Hey, I have another remark regarding HARM defence. I think it is a DCS bug but it may be possible to go around it.
It is a problem with "enableEmission" that I mentioned at DCS here https://forum.dcs.world/topic/312725-harm-seeker-sees-radars-in-too-even-when-they-are-turned-off/#comment-5087976. Do note that this only happens in multiplayer.
To summarize : turning a radar off with "enableEmission(false)", as is done by Skynet, will not avoid HARM tracking. Turning AI off as well will do it though. In fact, we can see that the P19 radar stops rotating when we do SetOnOff(false), but not when enableEmission(false).
I'll do some more testing on this and maybe propose an improvement for Skynet.

Solution:
when a SAM is defending against a HARM use the ai off command. This would allow the HARM to miss. Using enable emission in other cases gives more flexibility like beeing able to move units. ai off does not allow for that.

**Comment by MacFlorent** [comment]
For testing purposes I modified the script to do "ai off" in the main goDark function, but what you propose here is way better !
If you need me to do some testing I'll be happy to help.

**Comment by walder** [comment]
I won't be at my dcs machine in the next two weeks, I will let you know once I have a build ready. I rarely get time to play dcs these days so having someone testing Skynet on multiplayer would be great👍

**Comment by walder** [comment]
@MacFlorent I added this to the dev branch version, could you test in multiplayer? If ok, I will release shortly. SAMs will only use ai of for harm defence

**Comment by MacFlorent** [comment]
Hello, I will test this as soon as possible (probably this weekend) and keep you updated.

**Comment by MacFlorent** [comment]
I just did a successful test. HARM defence is working again. Thank you for your great work.

I plan to do some more testingnext week, so you can wait a bit before releasing, or not, as you prefer. I will keep you updated in any case.

Note that since radars are still turned off with `enableEmission` outside of the HARM defence, they will be visible on the HARM TOO page even when they are turned off. I don't think it's a big issue.
![image](https://user-images.githubusercontent.com/5670081/218338936-c72aeca4-0639-4f10-8ec8-1516be335f65.png)


### Test 1 (control)
`Using release 09.02.2023 1925Z`
_Step 1_
Site is off. Not visible on RWR. Visible on the HARM TOO.
_Step 2_
Site turns on. Visible on RWR. Still visible on the HARM TOO.
_Step 3_
HARM fired.
Site turns off. Not visible on RWR. Still visible on the HARM TOO.
HARM kills.
 
### Test 2
`Using develop 10.02.2023 1756Z`
_Step 1_
Site is off. Not visible on RWR. _Visible on the HARM TOO (not ideal)_.
_Step 2_
Site turns on. Visible on RWR. Still visible on the HARM TOO.
Step 3
HARM fired.
Site turns off. Not visible on RWR. _Not visible on the HARM TOO (test OK)_.
_HARM misses (test OK)_.

**Comment by MacFlorent** [comment]
Sidenote : the underlying DCS issue has been acknowledged by ED.
https://forum.dcs.world/topic/312725-harm-seeker-sees-radars-in-too-even-when-they-are-turned-off/?do=findComment&comment=5153043

**Comment by walder** [comment]
Thanks, if ED fixes that I will remove the ai on off, sees related the bug where the harm glides to the target and the radar shows up on the HARM seeker.

**Comment by MacFlorent** [comment]
I found an issue.
If a HARM is fired at a SAM radar while it is not yet active then :
- the radar will not enter HARM defence because it is already off
- it will stay off with `enableEmission`
- the HARM will see it and kill it

I did not have time to check the code, but I guess the solution would be to enter HARM defence even if the radar is off.

**Comment by walder** [comment]
So ai off would still be required, basically how skynet worked about a year ago. I hope ed can takle this bug so we can stick to setEmission

**Comment by MacFlorent** [comment]
Indeed the core problem here is that with `enableEmission`, the HARMs still see the radar (in MP only). Going fully back to `setAi` should be simple enough to do, and to rollback as well. This is what I did in my test correction back in november. It has the big advantage of code simplicity and ease of switching from one technique to the other.

If it were up to me, I would probably do that. With an optional activation even, with the default staying at `enableEmission`.
Like so : 
![image](https://user-images.githubusercontent.com/5670081/221575226-32ee1c1b-d38f-4346-97e5-f3b7219f4105.png)
![image](https://user-images.githubusercontent.com/5670081/221576765-7761a911-aef3-407d-9ecf-d9aafe4c7327.png)

I can do the modification and PR it if you think it's a good idea. It will probably be a bit more complicated, especially with the need to call `setupSAMSitesAndThenActivate` again.

**Comment by MacFlorent** [comment]
Hello, another info on that. Tested with SA-11 and SA-15.
- A player connects to a server while the radars are off (`enableEmission ` off)
- They are then turned on, appear on the RWR. **But the HARM _does not_ see them**.

This is kind of the reverse of problem encountered with the SA-3/SA-3. Still an ED bug of course, not a Skynet issue, and another check in the "hope they will correct that soon" column.

**Comment by MacFlorent** [comment]
I did some tests with 2.8.3 and as far as I can tell `enableEmission` is now working fine.
